---
stages: [build]

workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

build:
  stage: build
  script:
  - |
    YEAR_MONTH=$(date -u +%Y.%m)
    TAG="v${YEAR_MONTH}.${CI_PIPELINE_IID}"
    echo "Building $CI_REGISTRY_IMAGE:$TAG"
    buildah login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    buildah bud -t "$CI_REGISTRY_IMAGE:$TAG" -t "$CI_REGISTRY_IMAGE:latest" .
    buildah push "$CI_REGISTRY_IMAGE:$TAG"
    buildah push "$CI_REGISTRY_IMAGE:latest"
